name: ciber_radar
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  wifi_scan: ^0.4.1+2
  flutter_blue_plus: ^2.1.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_fonts: ^7.0.2
  path_provider: ^2.1.5
  csv: ^6.0.0
  sensors_plus: ^6.1.0
  network_info_plus: ^6.1.0
  nsd: ^4.1.0
  pdf: ^3.10.0
  printing: ^5.11.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # He añadido esto aquí:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

# CONFIGURACIÓN DE LOS ICONOS (Añadido al final)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  # AÑADE ESTO PARA MOVILES MODERNOS:
  adaptive_icon_background: "#000000" # O el color de fondo que quieras (negro)
  adaptive_icon_foreground: "assets/icon.png" # Tu misma imagen